server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
      database: 0
      lettuce:
        pool:
          # 最大连接数（默认8）
          max-active: 8
          # 最大空闲连接（默认8）
          max-idle: 8
          # 最小空闲连接（默认0）
          min-idle: 2
          # 最大等待时间（获取连接时的最长等待时间，单位毫秒，-1表示无限制）
          max-wait: 1000ms

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-cn-lf64is1r90004m1o.rwlb.rds.aliyuncs.com:3306/amy?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: ashen
    password: Lyuanshen520
    type: com.mchange.v2.c3p0.ComboPooledDataSource

jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  online-key: "app_online_token:"
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000
  resource-permission-key: "resources_permission:"
  client-header: XPLATFORM

file:
  poster-root: E:\workspace\amy\resource\poster
  image-ext: .webp
  avatar-resource-prefix: /resource/avatar
  avatar-root: C:\Users\shen\Documents\AMY\resource\avatar
  poster-resource-prefix: /resource/poster
  video-resource-prefix: /resource/video
  video-roots:
    - { name: 'base', order: 1, path: E:\workspace\amy\resource\video }
  enable-video-root: base
  upload-cache-key: 'upload-file:'


ffmpeg:
  ffmpeg-executor-path: E:\workspace\ONLYFUCK\.resource\bin\ffmpeg.exe
  ffprobe-executor-path: E:\workspace\ONLYFUCK\.resource\bin\ffprobe.exe

login:
  single-login: true

archive-repo:
  amy-archive-directory: amy
  root: C:\Users\shen\Documents\AMY\resource\archive
